sudo: required
services:
  - docker

before_install:
  - docker build -t sanjaynamdeo/frontend -f Dockerfile.dev .

script:
  - docker run sanjaynamdeo/frontend npm run test -- --coverage

deploy:
  provider: heroku
  api_key: '$HEROKU_API_KEY'
  app: docker-react-burger-builder
